name: ARM KVM Weekly Analysis

on:
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:
    inputs:
      days_back:
        description: 'Days to analyze'
        required: false
        default: '7'
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install markdown click
    
    - name: Configure Git
      run: |
        git config --global user.name "ARM KVM Bot"
        git config --global user.email "bot@arm-kvm.github.io"
    
    - name: Set timezone
      run: sudo timedatectl set-timezone Asia/Shanghai
    
    - name: Run analysis
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENTS: ${{ vars.EMAIL_RECIPIENTS }}
      run: |
        DAYS_BACK="${{ github.event.inputs.days_back || '7' }}"
        END_DATE=$(date +%Y-%m-%d)
        START_DATE=$(date -d "${DAYS_BACK} days ago" +%Y-%m-%d)
        echo "Analysis period: ${START_DATE} to ${END_DATE}"
        python analyze.py main --since ${START_DATE} --until ${END_DATE} --output results --language zh --verify-completeness --send-notifications
    
    - name: Generate HTML
      run: |
        LATEST_DIR=$(find results -name "20*" -type d | sort | tail -1)
        if [ -n "$LATEST_DIR" ]; then
          python html_generator.py --results-dir "$LATEST_DIR" --github-repo "https://onlinefchen.github.io/kvmarm-robot"
        fi
    
    - name: Prepare Pages
      run: |
        mkdir -p docs/reports
        LATEST_DIR=$(find results -name "20*" -type d | sort | tail -1)
        if [ -n "$LATEST_DIR" ]; then
          DATE_DIR=$(basename "$LATEST_DIR")
          cp -r "$LATEST_DIR" "docs/reports/$DATE_DIR"
          if [ -f "$LATEST_DIR/report.html" ]; then
            cp "$LATEST_DIR/report.html" "docs/reports/$DATE_DIR/index.html"
          fi
        fi
    
    - name: Create homepage
      run: |
        cat > docs/index.html << 'HTMLEOF'
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <title>ARM KVM Analysis Reports</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { background: #2c3e50; color: white; padding: 20px; border-radius: 10px; }
        .content { margin: 20px 0; }
        .report-card { border: 1px solid #ddd; padding: 15px; margin: 10px 0; border-radius: 8px; }
        .link { display: inline-block; background: #3498db; color: white; padding: 8px 16px; text-decoration: none; border-radius: 4px; margin: 5px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>ARM KVM Mailing List Analysis</h1>
        <p>Automated Technical Analysis • Weekly Updates</p>
    </div>
    <div class="content">
        <h2>Latest Reports</h2>
HTMLEOF
        
        for report_dir in docs/reports/*/; do
          if [ -d "$report_dir" ]; then
            date=$(basename "$report_dir")
            echo "        <div class=\"report-card\">" >> docs/index.html
            echo "            <h3>$date Report</h3>" >> docs/index.html
            echo "            <a href=\"reports/$date/\" class=\"link\">View Report</a>" >> docs/index.html
            echo "            <a href=\"reports/$date/analysis_report_zh.md\" class=\"link\">Markdown</a>" >> docs/index.html
            echo "        </div>" >> docs/index.html
          fi
        done
        
        cat >> docs/index.html << 'HTMLEOF'
    </div>
</body>
</html>
HTMLEOF
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: analysis-results
        path: results/
        retention-days: 30
    
    - name: Configure Pages
      uses: actions/configure-pages@v4
    
    - name: Upload Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs
    
    - name: Deploy Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
    - name: Send notification
      if: success()
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENTS: ${{ vars.EMAIL_RECIPIENTS }}
      run: |
        if [ -n "$EMAIL_USER" ] && [ -n "$EMAIL_PASSWORD" ] && [ -n "$EMAIL_RECIPIENTS" ]; then
          LATEST_DIR=$(find results -name "20*" -type d | sort | tail -1)
          DATE_STR=$(basename "$LATEST_DIR" 2>/dev/null || date +%Y-%m-%d)
          
          python3 -c "
import smtplib
import os
from email.mime.text import MIMEText
from datetime import datetime

user = os.getenv('EMAIL_USER')
password = os.getenv('EMAIL_PASSWORD')
recipients = os.getenv('EMAIL_RECIPIENTS', '').split(',')
date_str = os.getenv('DATE_STR', '')

content = f'''ARM KVM Weekly Report - {date_str}

Analysis completed successfully. View the detailed report online.

Online Report: https://onlinefchen.github.io/kvmarm-robot/reports/{date_str}/
All Reports: https://onlinefchen.github.io/kvmarm-robot

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} (GMT+8)
'''

msg = MIMEText(content, 'plain', 'utf-8')
msg['Subject'] = f'ARM KVM Weekly Report - {date_str}'
msg['From'] = user
msg['To'] = ', '.join([r.strip() for r in recipients if r.strip()])

with smtplib.SMTP('smtp.gmail.com', 587) as server:
    server.starttls()
    server.login(user, password)
    server.send_message(msg)

print('Email notification sent successfully')
" DATE_STR="$DATE_STR"
        else
          echo "Email configuration incomplete, skipping notification"
        fi